/**
 * FileParser — uses web-tree-sitter (WASM) to extract symbols from source files.
 *
 * Supported languages: TypeScript, JavaScript, Python, Java, Go, Rust, C/C++
 */

import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { glob } from 'glob';
import { CodeNode, CodeEdge, NodeType, EdgeType } from '../graph/GraphStore';
import { Logger } from '../../utils/Logger';

// Language → WASM grammar file mapping
const LANGUAGE_MAP: Record<string, { exts: string[]; grammar: string }> = {
  typescript:  { exts: ['.ts', '.tsx'], grammar: 'tree-sitter-typescript.wasm' },
  javascript:  { exts: ['.js', '.jsx', '.mjs'], grammar: 'tree-sitter-javascript.wasm' },
  python:      { exts: ['.py'], grammar: 'tree-sitter-python.wasm' },
  java:        { exts: ['.java'], grammar: 'tree-sitter-java.wasm' },
  go:          { exts: ['.go'], grammar: 'tree-sitter-go.wasm' },
  rust:        { exts: ['.rs'], grammar: 'tree-sitter-rust.wasm' },
  cpp:         { exts: ['.cpp', '.cc', '.cxx', '.h', '.hpp', '.c'], grammar: 'tree-sitter-cpp.wasm' },
};

export class FileParser {
  private readonly workspaceRoot: string;
  private readonly extensionRoot: string;
  private Parser: any = null;
  private languages: Map<string, any> = new Map();
  private initialized = false;

  constructor(workspaceRoot: string, extensionRoot: string) {
    this.workspaceRoot = workspaceRoot;
    this.extensionRoot = extensionRoot;
  }

  private async ensureInitialized(): Promise<void> {
    if (this.initialized) return;
    const TreeSitter = await import('web-tree-sitter');

    const wasmPath = path.join(this.extensionRoot, 'node_modules', 'web-tree-sitter', 'tree-sitter.wasm');

    await TreeSitter.default.init({
      locateFile: () => wasmPath
    });

    this.Parser = TreeSitter.default;
    this.initialized = true;
    Logger.info('Tree-sitter initialized');
  }

  async parseWorkspace(): Promise<{ nodes: CodeNode[], edges: CodeEdge[] }> {
    await this.ensureInitialized();
    const config = await import('vscode').then(v => v.workspace.getConfiguration('semanticKG'));
    const excludePatterns: string[] = config.get('excludePatterns', [
      '**/node_modules/**', '**/.git/**', '**/dist/**', '**/out/**',
    ]);

    const allExtensions = Object.values(LANGUAGE_MAP).flatMap(l => l.exts);
    const pattern = `**/*{${allExtensions.join(',')}}`;

    
    const files = await glob(pattern, {
      cwd: this.workspaceRoot,
      ignore: excludePatterns,
      absolute: true,
    });

    Logger.info(`Parsing ${files.length} files...`);
    const allNodes: CodeNode[] = [];
    const allEdges: CodeEdge[] = [];

    for (const filePath of files) {
      try {
        const { nodes, edges } = await this.parseFile(filePath);
        allNodes.push(...nodes);
        allEdges.push(...edges);
      } catch (err) {
        Logger.warn(`Skip ${filePath}: ${err}`);
      }
    }

    return { nodes: allNodes, edges: allEdges };
  }

  async parseFile(filePath: string): Promise<{ nodes: CodeNode[], edges: CodeEdge[] }>{
    await this.ensureInitialized();
    const ext = path.extname(filePath).toLowerCase();
    const langEntry = Object.entries(LANGUAGE_MAP).find(([, v]) => v.exts.includes(ext));
    if (!langEntry) return { nodes: [], edges: [] };

    const [langName] = langEntry;
    const code = fs.readFileSync(filePath, 'utf-8');
    const checksum = crypto.createHash('sha256').update(code).digest('hex').slice(0, 16);
    const relPath = path.relative(this.workspaceRoot, filePath);

    const nodes: CodeNode[] = [];
    const edges: CodeEdge[] = [];

    // File node (The root parent for CONTAINS edges)
    const fileNodeId = relPath;
    nodes.push({
      id: fileNodeId,
      type: 'file',
      name: relPath,
      filePath,
      signature: '',
      docstring: '',
      communityId: 0,
      checksum,
      isAutoGenerated: false,
      startLine: 0,
      endLine: code.split('\n').length,
    });

    try {
      const language = await this.loadLanguage(langName, langEntry[1].grammar);
      const parser = new this.Parser();
      parser.setLanguage(language);
      const tree = parser.parse(code);
      
      this.extractSymbols(tree.rootNode, code, filePath, relPath, nodes, edges);
      
      tree.delete();
    } catch (err) {
      Logger.warn(`Tree-sitter parse failed for ${filePath}, using regex fallback: ${err}`);
      this.regexFallbackExtract(code, filePath, relPath, nodes, edges);
    }

    return { nodes, edges };
  }

  private async loadLanguage(langName: string, grammarFile: string): Promise<any> {
    if (this.languages.has(langName)) return this.languages.get(langName);

    const grammarPath = path.join(this.extensionRoot, 'grammars', grammarFile);
    if (!fs.existsSync(grammarPath)) {
      throw new Error(`Grammar not found: ${grammarPath}`);
    }

    const lang = await this.Parser.Language.load(grammarPath);
    this.languages.set(langName, lang);
    return lang;
  }

  private extractSymbols(
    rootNode: any,
    code: string,
    filePath: string,
    relPath: string,
    nodes: CodeNode[],
    edges: CodeEdge[] 
  ): void {
    const lines = code.split('\n');
    const fileNodeId = relPath; 

    const walk = (node: any, parentId: string, parentClass?: string) => { 
      const type = node.type as string;

      if (type === 'function_declaration' || type === 'function_definition' ||
          type === 'method_definition' || type === 'function_item') {
            
        const nameNode = node.childForFieldName?.('name') ?? node.children?.find((c: any) => c.type === 'identifier');
        
        if (!nameNode) { node.children?.forEach((c: any) => walk(c, parentId, parentClass)); return; }

        const name = nameNode.text;
        const fullId = parentClass ? `${relPath}:${parentClass}.${name}` : `${relPath}:${name}`;
        const docstring = extractDocstring(node, lines);
        const signature = extractSignature(node, code);

        nodes.push({
          id: fullId,
          type: parentClass ? 'method' : 'function',
          name,
          filePath,
          signature,
          docstring,
          communityId: 0,
          checksum: crypto.createHash('sha256').update(node.text).digest('hex').slice(0, 16),
          isAutoGenerated: false,
          startLine: node.startPosition.row,
          endLine: node.endPosition.row,
        });

        edges.push({ sourceId: parentId, targetId: fullId, relationType: 'CONTAINS' });
        node.children?.forEach((c: any) => walk(c, fullId, parentClass));

      } else if (type === 'class_declaration' || type === 'class_definition') {
        const nameNode = node.childForFieldName?.('name') ?? node.children?.find((c: any) => c.type === 'identifier' || c.type === 'type_identifier');
        
        if (!nameNode) { node.children?.forEach((c: any) => walk(c, parentId)); return; }

        const name = nameNode.text;
        const fullId = `${relPath}:${name}`;
        const docstring = extractDocstring(node, lines);

        nodes.push({
          id: fullId,
          type: 'class',
          name,
          filePath,
          signature: `class ${name}`,
          docstring,
          communityId: 0,
          checksum: crypto.createHash('sha256').update(node.text.slice(0, 200)).digest('hex').slice(0, 16),
          isAutoGenerated: false,
          startLine: node.startPosition.row,
          endLine: node.endPosition.row,
        });

        edges.push({ sourceId: parentId, targetId: fullId, relationType: 'CONTAINS' });

        // === EXTENDS & IMPLEMENTS LOGIC FOR CLASSES ===
        // Look for AST nodes that signify inheritance or interfaces
        const heritageNodes = node.children?.filter((c: any) =>
          ['class_heritage', 'superclass', 'base_classes', 'interfaces'].includes(c.type)
        ) || [];

        heritageNodes.forEach((heritage: any) => {
          // Recursive scanner to find all type identifiers inside the heritage clause
          const findTypes = (n: any, currentRelation: EdgeType) => {
            // Switch relation context if we enter an implements/extends block
            if (n.type === 'extends_clause' || n.type === 'superclass' || n.type === 'base_classes') {
              currentRelation = 'EXTENDS';
            } else if (n.type === 'implements_clause' || n.type === 'interfaces') {
              currentRelation = 'IMPLEMENTS';
            }

            if (n.type === 'type_identifier' || n.type === 'identifier') {
              edges.push({
                sourceId: fullId,
                targetId: `${relPath}:${n.text}`, // Naive local resolution
                relationType: currentRelation
              });
            } else {
              n.children?.forEach((child: any) => findTypes(child, currentRelation));
            }
          };

          const defaultRelation: EdgeType = heritage.type === 'interfaces' ? 'IMPLEMENTS' : 'EXTENDS';
          findTypes(heritage, defaultRelation);
        });
        // ==============================================

        node.children?.forEach((c: any) => walk(c, fullId, name));

      } else if (type === 'interface_declaration') {
        const nameNode = node.children?.find((c: any) => c.type === 'type_identifier');
        
        if (!nameNode) { node.children?.forEach((c: any) => walk(c, parentId)); return; }

        const name = nameNode.text;
        const fullId = `${relPath}:${name}`;

        nodes.push({
          id: fullId,
          type: 'interface',
          name,
          filePath,
          signature: `interface ${name}`,
          docstring: extractDocstring(node, lines),
          communityId: 0,
          checksum: '',
          isAutoGenerated: false,
          startLine: node.startPosition.row,
          endLine: node.endPosition.row,
        });

        edges.push({ sourceId: parentId, targetId: fullId, relationType: 'CONTAINS' });

        // === EXTENDS LOGIC FOR INTERFACES ===
        // Interfaces can extend other interfaces!
        const heritageNodes = node.children?.filter((c: any) => ['extends_clause'].includes(c.type)) || [];
        heritageNodes.forEach((heritage: any) => {
           const findTypes = (n: any) => {
              if (n.type === 'type_identifier' || n.type === 'identifier') {
                 edges.push({ sourceId: fullId, targetId: `${relPath}:${n.text}`, relationType: 'EXTENDS' });
              } else {
                 n.children?.forEach((child: any) => findTypes(child));
              }
           };
           findTypes(heritage);
        });
        // ====================================

        node.children?.forEach((c: any) => walk(c, fullId, name));

      } else {
        node.children?.forEach((c: any) => walk(c, parentId, parentClass));
      }
    };

    walk(rootNode, fileNodeId);
  }

  private regexFallbackExtract(
    code: string,
    filePath: string,
    relPath: string,
    nodes: CodeNode[],
    edges: CodeEdge[]
  ): void {
    const lines = code.split('\n');

    const fnRegex = /^(?:export\s+)?(?:async\s+)?(?:function\s+(\w+)|(?:const|let|var)\s+(\w+)\s*=\s*(?:async\s*)?\(|def\s+(\w+))/gm;
    const classRegex = /^(?:export\s+)?class\s+(\w+)/gm;

    let match: RegExpExecArray | null;

    while ((match = fnRegex.exec(code)) !== null) {
      const name = match[1] ?? match[2] ?? match[3];
      if (!name) continue;
      const lineNo = code.slice(0, match.index).split('\n').length - 1;
      const fullId = `${relPath}:${name}`;
      nodes.push({
        id: `${relPath}:${name}`,
        type: 'function',
        name,
        filePath,
        signature: match[0].trim(),
        docstring: '',
        communityId: 0,
        checksum: '',
        isAutoGenerated: false,
        startLine: lineNo,
        endLine: lineNo,
      });
      edges.push({ sourceId: relPath, targetId: fullId, relationType: 'CONTAINS' });
    }

    while ((match = classRegex.exec(code)) !== null) {
      const name = match[1];
      const lineNo = code.slice(0, match.index).split('\n').length - 1;
      const fullId = `${relPath}:${name}`;
      nodes.push({
        id: `${relPath}:${name}`,
        type: 'class',
        name,
        filePath,
        signature: `class ${name}`,
        docstring: '',
        communityId: 0,
        checksum: '',
        isAutoGenerated: false,
        startLine: lineNo,
        endLine: lineNo,
      });
      edges.push({ sourceId: relPath, targetId: fullId, relationType: 'CONTAINS' });
    }
  }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function extractDocstring(node: any, lines: string[]): string {
  const startLine = node.startPosition?.row ?? 0;
  if (startLine === 0) return '';

  const prevLine = lines[startLine - 1]?.trim() ?? '';

  if (prevLine.startsWith('//') || prevLine.startsWith('#')) {
    return prevLine.replace(/^[/#\s*]+/, '').trim();
  }

  if (prevLine.startsWith('*/')) {
    const commentLines: string[] = [];
    for (let i = startLine - 2; i >= 0; i--) {
      const l = lines[i].trim();
      if (l.startsWith('/*') || l.startsWith('/**')) break;
      commentLines.unshift(l.replace(/^\*\s?/, ''));
    }
    return commentLines.join(' ').trim();
  }

  const bodyNode = node.childForFieldName?.('body');
  if (bodyNode) {
    const first = bodyNode.children?.[0];
    if (first?.type === 'expression_statement') {
      const str = first.children?.[0];
      if (str?.type === 'string') {
        return str.text.replace(/^['"`]{1,3}|['"`]{1,3}$/g, '').trim();
      }
    }
  }

  return '';
}

function extractSignature(node: any, code: string): string {
  const bodyNode = node.childForFieldName?.('body');
  if (bodyNode) {
    return code.slice(node.startIndex, bodyNode.startIndex).replace(/\s+/g, ' ').trim();
  }
  return node.text?.split('\n')[0]?.trim() ?? '';
}