/**
 * GraphStore — sql.js (WASM) backed knowledge graph.
 *
 * Schema v2 additions:
 *   nodes.modifiers     — JSON array of keywords (public, static, async, etc.)
 *   nodes.class_name    — enclosing class name (for methods)
 *   nodes.package_name  — package/module name
 */

import * as path from 'path';
import * as fs from 'fs';
import { Logger } from '../../utils/Logger';

export type NodeType = 'file' | 'class' | 'function' | 'method' | 'interface';
export type EdgeType = 'CONTAINS' | 'CALLS' | 'IMPORTS' | 'EXTENDS' | 'IMPLEMENTS';

export interface CodeNode {
  id: string;
  type: NodeType;
  name: string;
  filePath: string;
  signature: string;
  docstring: string;
  communityId: number;
  checksum: string;
  isAutoGenerated: boolean;
  startLine: number;
  endLine: number;
  modifiers: string[];
  className: string | null;
  packageName: string | null;
}

export interface CodeEdge {
  sourceId: string;
  targetId: string;
  relationType: EdgeType;
}

export interface SearchResult {
  node: CodeNode;
  score: number;
}

type SqlJsDatabase = any;

export class GraphStore {
  private db: SqlJsDatabase = null;
  private readonly dbPath: string;
  private saveTimer: ReturnType<typeof setTimeout> | null = null;

  constructor(storagePath: string, _workspaceRoot: string) {
    fs.mkdirSync(storagePath, { recursive: true });
    this.dbPath = path.join(storagePath, 'knowledge-graph.db');
  }

  async initialize(): Promise<void> {
    const sqlJsPath = require.resolve('sql.js');
    const sqlJsDir  = path.dirname(sqlJsPath);
    const wasmPath  = path.join(sqlJsDir, 'sql-wasm.wasm');
    const initSqlJs = require('sql.js');
    const SQL = await initSqlJs({ locateFile: () => wasmPath });

    if (fs.existsSync(this.dbPath)) {
      this.db = new SQL.Database(fs.readFileSync(this.dbPath));
      Logger.info(`GraphStore loaded from ${this.dbPath}`);
    } else {
      this.db = new SQL.Database();
      Logger.info(`GraphStore created at ${this.dbPath}`);
    }

    this.exec('PRAGMA foreign_keys = ON;');
    this.runMigrations();
    this.persist();
  }

  private columnExists(tableName: string, columnName: string): boolean {
    try {
      const result = this.query<any>(`PRAGMA table_info(${tableName})`, []);
      return result.some(col => col.name === columnName);
    } catch {
      return false;
    }
  }

  private runMigrations(): void {
    this.exec(`
      CREATE TABLE IF NOT EXISTS nodes (
        id                TEXT PRIMARY KEY,
        type              TEXT NOT NULL,
        name              TEXT NOT NULL,
        file_path         TEXT NOT NULL,
        signature         TEXT DEFAULT '',
        docstring         TEXT DEFAULT '',
        community_id      INTEGER DEFAULT 0,
        checksum          TEXT DEFAULT '',
        is_auto_generated INTEGER DEFAULT 0,
        start_line        INTEGER DEFAULT 0,
        end_line          INTEGER DEFAULT 0,
        modifiers         TEXT DEFAULT '[]',
        class_name        TEXT DEFAULT NULL,
        package_name      TEXT DEFAULT NULL,
        updated_at        INTEGER DEFAULT 0
      );

      CREATE TABLE IF NOT EXISTS edges (
        id            INTEGER PRIMARY KEY AUTOINCREMENT,
        source_id     TEXT NOT NULL,
        target_id     TEXT NOT NULL,
        relation_type TEXT NOT NULL,
        UNIQUE(source_id, target_id, relation_type)
      );

      CREATE INDEX IF NOT EXISTS idx_nodes_file    ON nodes(file_path);
      CREATE INDEX IF NOT EXISTS idx_nodes_type    ON nodes(type);
      CREATE INDEX IF NOT EXISTS idx_nodes_name    ON nodes(name);
      CREATE INDEX IF NOT EXISTS idx_nodes_class   ON nodes(class_name);
      CREATE INDEX IF NOT EXISTS idx_nodes_pkg     ON nodes(package_name);
      CREATE INDEX IF NOT EXISTS idx_edges_source  ON edges(source_id);
      CREATE INDEX IF NOT EXISTS idx_edges_target  ON edges(target_id);
      CREATE INDEX IF NOT EXISTS idx_edges_type    ON edges(relation_type);

      CREATE TABLE IF NOT EXISTS embeddings (
        node_id TEXT PRIMARY KEY,
        vector  BLOB NOT NULL,
        dims    INTEGER NOT NULL DEFAULT 384
      );
    `);

    // Add new columns to existing DB if upgrading from v1
    if (!this.columnExists('nodes', 'modifiers')) {
      this.exec(`ALTER TABLE nodes ADD COLUMN modifiers TEXT DEFAULT '[]'`);
    }
    if (!this.columnExists('nodes', 'class_name')) {
      this.exec(`ALTER TABLE nodes ADD COLUMN class_name TEXT DEFAULT NULL`);
    }
    if (!this.columnExists('nodes', 'package_name')) {
      this.exec(`ALTER TABLE nodes ADD COLUMN package_name TEXT DEFAULT NULL`);
    }
  }

  // ── Write operations ───────────────────────────────────────────────────────

  async upsertNodes(nodes: CodeNode[]): Promise<void> {
    if (nodes.length === 0) return;
    const sql = `
      INSERT INTO nodes
        (id, type, name, file_path, signature, docstring, community_id,
         checksum, is_auto_generated, start_line, end_line,
         modifiers, class_name, package_name, updated_at)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
      ON CONFLICT(id) DO UPDATE SET
        type              = excluded.type,
        name              = excluded.name,
        file_path         = excluded.file_path,
        signature         = excluded.signature,
        docstring         = CASE WHEN excluded.docstring != '' THEN excluded.docstring ELSE nodes.docstring END,
        checksum          = excluded.checksum,
        is_auto_generated = excluded.is_auto_generated,
        start_line        = excluded.start_line,
        end_line          = excluded.end_line,
        modifiers         = excluded.modifiers,
        class_name        = excluded.class_name,
        package_name      = excluded.package_name,
        updated_at        = excluded.updated_at
    `;
    const stmt = this.db.prepare(sql);
    const now = Math.floor(Date.now() / 1000);
    for (const n of nodes) {
      stmt.run([
        n.id, n.type, n.name, n.filePath, n.signature, n.docstring,
        n.communityId, n.checksum, n.isAutoGenerated ? 1 : 0,
        n.startLine, n.endLine,
        JSON.stringify(n.modifiers ?? []),
        n.className ?? null,
        n.packageName ?? null,
        now,
      ]);
    }
    stmt.free();
    this.schedulePersist();
  }

  upsertEdges(edges: CodeEdge[]): void {
    if (edges.length === 0) return;
    const stmt = this.db.prepare(`
      INSERT OR IGNORE INTO edges (source_id, target_id, relation_type) VALUES (?,?,?)
    `);
    for (const e of edges) stmt.run([e.sourceId, e.targetId, e.relationType]);
    stmt.free();
    this.schedulePersist();
  }

  storeEmbedding(nodeId: string, vector: Float32Array): void {
    const stmt = this.db.prepare(`INSERT OR REPLACE INTO embeddings (node_id, vector, dims) VALUES (?,?,?)`);
    stmt.run([nodeId, Buffer.from(vector.buffer), vector.length]);
    stmt.free();
    this.schedulePersist();
  }

  updateDocstring(nodeId: string, docstring: string, isAutoGenerated: boolean): void {
    const stmt = this.db.prepare(`UPDATE nodes SET docstring=?, is_auto_generated=? WHERE id=?`);
    stmt.run([docstring, isAutoGenerated ? 1 : 0, nodeId]);
    stmt.free();
    this.schedulePersist();
  }

  updateCommunityId(nodeId: string, communityId: number): void {
    const stmt = this.db.prepare(`UPDATE nodes SET community_id=? WHERE id=?`);
    stmt.run([communityId, nodeId]);
    stmt.free();
  }

  removeFile(filePath: string): void {
    const ids = this.query<{ id: string }>(`SELECT id FROM nodes WHERE file_path=?`, [filePath]).map(r => r.id);
    for (const id of ids) {
      this.run(`DELETE FROM edges WHERE source_id=? OR target_id=?`, [id, id]);
      this.run(`DELETE FROM embeddings WHERE node_id=?`, [id]);
    }
    this.run(`DELETE FROM nodes WHERE file_path=?`, [filePath]);
    this.schedulePersist();
  }

  // ── Read operations ────────────────────────────────────────────────────────

  getNode(id: string): CodeNode | null {
    const rows = this.query<any>(`SELECT * FROM nodes WHERE id=?`, [id]);
    return rows.length ? this.rowToNode(rows[0]) : null;
  }

  // ── Utility operations ─────────────────────────────────────────────────────

  /**
   * Generates a clickable link/URI for a specific node to open it in an editor.
   * * @param id The ID of the CodeNode
   * @param editor The target editor/environment (defaults to 'vscode')
   * @returns A formatted string link, or null if the node doesn't exist
   */
  getNodeEditorLink(id: string, editor: 'vscode' | 'terminal' | 'github' = 'vscode'): string | null {
    const node = this.getNode(id);
    if (!node) return null;

    // Resolve absolute path if your UI requires it (assuming _workspaceRoot is stored)
    // If your filePath is already absolute, you can skip path.resolve
    const absolutePath = path.resolve(this.dbPath, '../../', node.filePath); // Adjust based on your workspace root logic

    switch (editor) {
      case 'vscode':
        // Example: vscode://file/c:/projects/my-app/src/main.ts:42
        return `vscode://file/${absolutePath}:${node.startLine}`;
        
      case 'terminal':
        // Example: src/main.ts:42
        return `${node.filePath}:${node.startLine}`;
        
      case 'github':
        // Example: src/main.ts#L42
        return `${node.filePath}#L${node.startLine}`;
        
      default:
        return `${node.filePath}:${node.startLine}`;
    }
  }

  getNodesByFile(filePath: string): CodeNode[] {
    return this.query<any>(`SELECT * FROM nodes WHERE file_path=?`, [filePath]).map(r => this.rowToNode(r));
  }

  getNeighbours(nodeId: string): { callers: CodeNode[]; callees: CodeNode[] } {
    const callees = this.query<any>(`
      SELECT n.* FROM nodes n JOIN edges e ON e.target_id=n.id
      WHERE e.source_id=? AND e.relation_type='CALLS'
    `, [nodeId]).map(r => this.rowToNode(r));

    const callers = this.query<any>(`
      SELECT n.* FROM nodes n JOIN edges e ON e.source_id=n.id
      WHERE e.target_id=? AND e.relation_type='CALLS'
    `, [nodeId]).map(r => this.rowToNode(r));

    return { callers, callees };
  }

  getBlastRadius(nodeId: string, maxDepth = 10): CodeNode[] {
    return this.query<any>(`
      WITH RECURSIVE blast(id, depth) AS (
        SELECT ?, 0
        UNION ALL
        SELECT e.target_id, blast.depth+1
        FROM edges e JOIN blast ON blast.id=e.source_id
        WHERE blast.depth < ? AND e.relation_type IN ('CALLS','IMPORTS')
      )
      SELECT DISTINCT n.* FROM nodes n JOIN blast ON blast.id=n.id
    `, [nodeId, maxDepth]).map(r => this.rowToNode(r));
  }

  searchKeyword(query: string, limit = 20): CodeNode[] {
    const like = `%${query}%`;
    return this.query<any>(
      `SELECT * FROM nodes WHERE name LIKE ? OR docstring LIKE ? OR signature LIKE ? LIMIT ?`,
      [like, like, like, limit]
    ).map(r => this.rowToNode(r));
  }

  searchSemantic(queryVector: Float32Array, limit = 10): SearchResult[] {
    const rows = this.query<any>(`SELECT n.*, e.vector FROM nodes n JOIN embeddings e ON e.node_id=n.id`, []);
    return rows
      .map(row => ({
        node: this.rowToNode(row),
        score: cosineSimilarity(queryVector, new Float32Array((row.vector as Buffer).buffer)),
      }))
      .sort((a, b) => b.score - a.score)
      .slice(0, limit);
  }

  getNodesWithoutEmbeddings(): CodeNode[] {
    return this.query<any>(`
      SELECT n.* FROM nodes n LEFT JOIN embeddings e ON e.node_id=n.id
      WHERE e.node_id IS NULL AND n.type != 'file'
    `, []).map(r => this.rowToNode(r));
  }

  getNodesWithoutDocstrings(): CodeNode[] {
    return this.query<any>(
      `SELECT * FROM nodes WHERE (docstring IS NULL OR docstring='') AND type IN ('function','method','class')`,
      []
    ).map(r => this.rowToNode(r));
  }

  getAllNodes(): CodeNode[] {
    return this.query<any>(`SELECT * FROM nodes`, []).map(r => this.rowToNode(r));
  }

  getAllEdges(): CodeEdge[] {
    return this.query<any>(`SELECT * FROM edges`, []).map(r => ({
      sourceId: r.source_id,
      targetId: r.target_id,
      relationType: r.relation_type as EdgeType,
    }));
  }

  getEdgesByType(type: EdgeType): CodeEdge[] {
    return this.query<any>(`SELECT * FROM edges WHERE relation_type=?`, [type]).map(r => ({
      sourceId: r.source_id,
      targetId: r.target_id,
      relationType: r.relation_type as EdgeType,
    }));
  }

  getStats(): { nodes: number; edges: number; withEmbeddings: number; byType: Record<string, number> } {
    const nodes          = this.query<any>(`SELECT COUNT(*) as c FROM nodes`, [])[0]?.c ?? 0;
    const edges          = this.query<any>(`SELECT COUNT(*) as c FROM edges`, [])[0]?.c ?? 0;
    const withEmbeddings = this.query<any>(`SELECT COUNT(*) as c FROM embeddings`, [])[0]?.c ?? 0;
    const byTypeRows     = this.query<any>(`SELECT type, COUNT(*) as c FROM nodes GROUP BY type`, []);
    const byType: Record<string, number> = {};
    byTypeRows.forEach(r => { byType[r.type] = r.c; });
    return { nodes, edges, withEmbeddings, byType };
  }

  close(): void {
    if (this.saveTimer) { clearTimeout(this.saveTimer); this.saveTimer = null; }
    this.persist();
    this.db?.close();
  }

  // ── Persistence ────────────────────────────────────────────────────────────

  persist(): void {
    if (!this.db) return;
    try {
      fs.writeFileSync(this.dbPath, Buffer.from(this.db.export()));
    } catch (err) {
      Logger.warn(`GraphStore persist failed: ${err}`);
    }
  }

  private schedulePersist(): void {
    if (this.saveTimer) clearTimeout(this.saveTimer);
    this.saveTimer = setTimeout(() => { this.persist(); this.saveTimer = null; }, 2000);
  }

  // ── sql.js helpers ─────────────────────────────────────────────────────────

  private exec(sql: string): void { this.db.run(sql); }

  private tryExec(sql: string): void {
    try { this.db.run(sql); } catch { /* column already exists */ }
  }

  private run(sql: string, params: any[]): void {
    const stmt = this.db.prepare(sql);
    stmt.run(params);
    stmt.free();
  }

  private query<T>(sql: string, params: any[]): T[] {
    const stmt = this.db.prepare(sql);
    stmt.bind(params);
    const results: T[] = [];
    while (stmt.step()) results.push(stmt.getAsObject() as unknown as T);
    stmt.free();
    return results;
  }

  private rowToNode(row: any): CodeNode {
    let modifiers: string[] = [];
    try { modifiers = JSON.parse(row.modifiers ?? '[]'); } catch { modifiers = []; }
    return {
      id:              row.id,
      type:            row.type as NodeType,
      name:            row.name,
      filePath:        row.file_path,
      signature:       row.signature   ?? '',
      docstring:       row.docstring   ?? '',
      communityId:     row.community_id ?? 0,
      checksum:        row.checksum    ?? '',
      isAutoGenerated: Boolean(row.is_auto_generated),
      startLine:       row.start_line  ?? 0,
      endLine:         row.end_line    ?? 0,
      modifiers,
      className:       row.class_name  ?? null,
      packageName:     row.package_name ?? null,
    };
  }
}

function cosineSimilarity(a: Float32Array, b: Float32Array): number {
  if (a.length !== b.length) return 0;
  let dot = 0, nA = 0, nB = 0;
  for (let i = 0; i < a.length; i++) { dot += a[i]*b[i]; nA += a[i]*a[i]; nB += b[i]*b[i]; }
  const d = Math.sqrt(nA) * Math.sqrt(nB);
  return d === 0 ? 0 : dot / d;
}